/* Generated By:JavaCC: Do not edit this line. ADQLGrammar200Constants.java */
package adql.parser.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ADQLGrammar200Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SQL_RESERVED_WORD = 2;
  /** RegularExpression Id. */
  int LEFT_PAR = 3;
  /** RegularExpression Id. */
  int RIGHT_PAR = 4;
  /** RegularExpression Id. */
  int DOT = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int EOQ = 7;
  /** RegularExpression Id. */
  int CONCAT = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int ASTERISK = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int BIT_AND = 13;
  /** RegularExpression Id. */
  int BIT_OR = 14;
  /** RegularExpression Id. */
  int BIT_XOR = 15;
  /** RegularExpression Id. */
  int BIT_NOT = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int NOT_EQUAL = 18;
  /** RegularExpression Id. */
  int LESS_THAN = 19;
  /** RegularExpression Id. */
  int LESS_EQUAL_THAN = 20;
  /** RegularExpression Id. */
  int GREATER_THAN = 21;
  /** RegularExpression Id. */
  int GREATER_EQUAL_THAN = 22;
  /** RegularExpression Id. */
  int SELECT = 23;
  /** RegularExpression Id. */
  int QUANTIFIER = 24;
  /** RegularExpression Id. */
  int TOP = 25;
  /** RegularExpression Id. */
  int FROM = 26;
  /** RegularExpression Id. */
  int AS = 27;
  /** RegularExpression Id. */
  int NATURAL = 28;
  /** RegularExpression Id. */
  int INNER = 29;
  /** RegularExpression Id. */
  int OUTER = 30;
  /** RegularExpression Id. */
  int RIGHT = 31;
  /** RegularExpression Id. */
  int LEFT = 32;
  /** RegularExpression Id. */
  int FULL = 33;
  /** RegularExpression Id. */
  int JOIN = 34;
  /** RegularExpression Id. */
  int ON = 35;
  /** RegularExpression Id. */
  int USING = 36;
  /** RegularExpression Id. */
  int WHERE = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int IS = 41;
  /** RegularExpression Id. */
  int NULL = 42;
  /** RegularExpression Id. */
  int BETWEEN = 43;
  /** RegularExpression Id. */
  int LIKE = 44;
  /** RegularExpression Id. */
  int IN = 45;
  /** RegularExpression Id. */
  int EXISTS = 46;
  /** RegularExpression Id. */
  int BY = 47;
  /** RegularExpression Id. */
  int GROUP = 48;
  /** RegularExpression Id. */
  int HAVING = 49;
  /** RegularExpression Id. */
  int ORDER = 50;
  /** RegularExpression Id. */
  int ASC = 51;
  /** RegularExpression Id. */
  int DESC = 52;
  /** RegularExpression Id. */
  int AVG = 53;
  /** RegularExpression Id. */
  int MAX = 54;
  /** RegularExpression Id. */
  int MIN = 55;
  /** RegularExpression Id. */
  int SUM = 56;
  /** RegularExpression Id. */
  int COUNT = 57;
  /** RegularExpression Id. */
  int BOX = 58;
  /** RegularExpression Id. */
  int CENTROID = 59;
  /** RegularExpression Id. */
  int CIRCLE = 60;
  /** RegularExpression Id. */
  int POINT = 61;
  /** RegularExpression Id. */
  int POLYGON = 62;
  /** RegularExpression Id. */
  int REGION = 63;
  /** RegularExpression Id. */
  int CONTAINS = 64;
  /** RegularExpression Id. */
  int INTERSECTS = 65;
  /** RegularExpression Id. */
  int AREA = 66;
  /** RegularExpression Id. */
  int COORD1 = 67;
  /** RegularExpression Id. */
  int COORD2 = 68;
  /** RegularExpression Id. */
  int COORDSYS = 69;
  /** RegularExpression Id. */
  int DISTANCE = 70;
  /** RegularExpression Id. */
  int ABS = 71;
  /** RegularExpression Id. */
  int CEILING = 72;
  /** RegularExpression Id. */
  int DEGREES = 73;
  /** RegularExpression Id. */
  int EXP = 74;
  /** RegularExpression Id. */
  int FLOOR = 75;
  /** RegularExpression Id. */
  int LOG = 76;
  /** RegularExpression Id. */
  int LOG10 = 77;
  /** RegularExpression Id. */
  int MOD = 78;
  /** RegularExpression Id. */
  int PI = 79;
  /** RegularExpression Id. */
  int POWER = 80;
  /** RegularExpression Id. */
  int RADIANS = 81;
  /** RegularExpression Id. */
  int RAND = 82;
  /** RegularExpression Id. */
  int ROUND = 83;
  /** RegularExpression Id. */
  int SQRT = 84;
  /** RegularExpression Id. */
  int TRUNCATE = 85;
  /** RegularExpression Id. */
  int ACOS = 86;
  /** RegularExpression Id. */
  int ASIN = 87;
  /** RegularExpression Id. */
  int ATAN = 88;
  /** RegularExpression Id. */
  int ATAN2 = 89;
  /** RegularExpression Id. */
  int COS = 90;
  /** RegularExpression Id. */
  int COT = 91;
  /** RegularExpression Id. */
  int SIN = 92;
  /** RegularExpression Id. */
  int TAN = 93;
  /** RegularExpression Id. */
  int STRING_LITERAL = 97;
  /** RegularExpression Id. */
  int SCIENTIFIC_NUMBER = 98;
  /** RegularExpression Id. */
  int UNSIGNED_FLOAT = 99;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER = 100;
  /** RegularExpression Id. */
  int DIGIT = 101;
  /** RegularExpression Id. */
  int DELIMITED_IDENTIFIER = 104;
  /** RegularExpression Id. */
  int REGULAR_IDENTIFIER_CANDIDATE = 105;
  /** RegularExpression Id. */
  int Letter = 106;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinString = 1;
  /** Lexical state. */
  int WithinDelimitedId = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<SQL_RESERVED_WORD>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"=\"",
    "<NOT_EQUAL>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"SELECT\"",
    "<QUANTIFIER>",
    "\"TOP\"",
    "\"FROM\"",
    "\"AS\"",
    "\"NATURAL\"",
    "\"INNER\"",
    "\"OUTER\"",
    "\"RIGHT\"",
    "\"LEFT\"",
    "\"FULL\"",
    "\"JOIN\"",
    "\"ON\"",
    "\"USING\"",
    "\"WHERE\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"IS\"",
    "\"NULL\"",
    "\"BETWEEN\"",
    "\"LIKE\"",
    "\"IN\"",
    "\"EXISTS\"",
    "\"BY\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"ORDER\"",
    "\"ASC\"",
    "\"DESC\"",
    "\"AVG\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"SUM\"",
    "\"COUNT\"",
    "\"BOX\"",
    "\"CENTROID\"",
    "\"CIRCLE\"",
    "\"POINT\"",
    "\"POLYGON\"",
    "\"REGION\"",
    "\"CONTAINS\"",
    "\"INTERSECTS\"",
    "\"AREA\"",
    "\"COORD1\"",
    "\"COORD2\"",
    "\"COORDSYS\"",
    "\"DISTANCE\"",
    "\"ABS\"",
    "\"CEILING\"",
    "\"DEGREES\"",
    "\"EXP\"",
    "\"FLOOR\"",
    "\"LOG\"",
    "\"LOG10\"",
    "\"MOD\"",
    "\"PI\"",
    "\"POWER\"",
    "\"RADIANS\"",
    "\"RAND\"",
    "\"ROUND\"",
    "\"SQRT\"",
    "\"TRUNCATE\"",
    "\"ACOS\"",
    "\"ASIN\"",
    "\"ATAN\"",
    "\"ATAN2\"",
    "\"COS\"",
    "\"COT\"",
    "\"SIN\"",
    "\"TAN\"",
    "<token of kind 94>",
    "\"\\\'\"",
    "<token of kind 96>",
    "\"\\\'\"",
    "<SCIENTIFIC_NUMBER>",
    "<UNSIGNED_FLOAT>",
    "<UNSIGNED_INTEGER>",
    "<DIGIT>",
    "\"\\\"\"",
    "<token of kind 103>",
    "\"\\\"\"",
    "<REGULAR_IDENTIFIER_CANDIDATE>",
    "<Letter>",
  };

}
